stage: 'dev'
profile: ''
acm_certificate: 'arn:aws:acm:us-east-1:710809157942:certificate/08e41ac8-bdb9-45c1-b953-eed4768918c5'
alias_domain: 'habeasdata-dev.libertyseguros.co'
cognito_auth_domain: 'https://intl-co-up-domain-habeas-data-dev.auth.us-east-1.amazoncognito.com'
logging_bucket: 'lmig-cloudfront-access-logs-710809157942-us-east-1.s3.amazonaws.com'
web_acl_id: !Join
          - ''
          - - 'arn:aws:wafv2:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':global/webacl/aws-cloudfront-webacl-external-block-'
            - 'dev-v1/3f63fcf7-c442-479f-98c0-34c248a620d9'

subnetIds:
  - 'subnet-c376d0a7'
  - 'subnet-ac6accc8'
  - 'subnet-d968cebd'
  - 'subnet-0f31d6b9d05e0619e'

securityGroupIds:
  - 'sg-062e1b3658b20104d'

tags:
  - 
    Key: "lm_app"
    Value: "Habeas Data"
  - 
    Key: "lm_troux_uid"
    Value: "1B730507-66B9-406B-ADF0-0DC68BC30743"  
  -
    Key: "lm_sbu"
    Value: "INTL"
  - 
    Key: "intl_country"
    Value: "CO"
  - 
    Key: "intl_region"
    Value: "LATAM"
  - 
    Key: "lm_app_env"
    Value: ${self:custom.stage}

stackTags:
  lm_app: 'Habeas Data'
  lm_troux_uid: '1B730507-66B9-406B-ADF0-0DC68BC30743'
  lm_sbu: INTL
  intl_country: CO
  intl_region: LATAM
  lm_app_env: ${self:custom.stage}


