stage: 'prod'
profile: ''
acm_certificate: 'arn:aws:acm:us-east-1:626569123605:certificate/06cbc6bf-cc48-4753-8c3c-31b60199ab94'
alias_domain: 'consultahabeasdata.libertyseguros.co'
cognito_auth_domain: ''
logging_bucket: 'lmig-cloudfront-access-logs-626569123605-us-east-1.s3.amazonaws.com'
web_acl_id: !Join
          - ''
          - - 'arn:aws:wafv2:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':global/webacl/aws-cloudfront-webacl-external-block-'
            - 'v1/ba2373cc-0596-4725-b214-7aaeb3143c6c'

securityGroupIds:
  - sg-05e49b77
  - sg-038657866ca67e90c
  - sg-03f8db4e0acd57a31
  - sg-07bba98ad9ea0b047
  - sg-0c44bd39ab17b5495

subnetIds:
  - subnet-e836d0b5

tags:
  - 
    Key: "lm_app"
    Value: "Habeas Data"
  - 
    Key: "lm_troux_uid"
    Value: "1B730507-66B9-406B-ADF0-0DC68BC30743"  
  -
    Key: "lm_sbu"
    Value: "INTL"
  - 
    Key: "intl_country"
    Value: "CO"
  - 
    Key: "intl_region"
    Value: "LATAM"
  - 
    Key: "lm_app_env"
    Value: ${self:custom.stage}

stackTags:
  lm_app: 'Habeas Data'
  lm_troux_uid: '1B730507-66B9-406B-ADF0-0DC68BC30743'
  lm_sbu: INTL
  intl_country: CO
  intl_region: LATAM
  lm_app_env: ${self:custom.stage}


